// Code generated by templ DO NOT EDIT.

package templates

import "github.com/a-h/templ"
import "context"
import "io"
import "github.com/joe-davidson1802/go-pact-consumer/models"
import "fmt"

func TimePage(times []models.TimeResponse) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		ctx, _ = templ.RenderedCSSClassesFromContext(ctx)
		_, err = io.WriteString(w, "<html>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<body>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<h1>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, templ.EscapeString("Times"))
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</h1>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "<ul>")
		if err != nil {
			return err
		}
		for _, t := range times {
			_, err = io.WriteString(w, "<li>")
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, templ.EscapeString(fmt.Sprintf("%s: %s", t.Zone, t.Time.Format("3:04PM"))))
			if err != nil {
				return err
			}
			_, err = io.WriteString(w, "</li>")
			if err != nil {
				return err
			}
		}
		_, err = io.WriteString(w, "</ul>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</body>")
		if err != nil {
			return err
		}
		_, err = io.WriteString(w, "</html>")
		if err != nil {
			return err
		}
		return err
	})
}

